// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDaaP2LkXC5EKv7bXmElsYTjf7FPrGTzM',
    appId: '1:915695183066:web:162df5e1e53b90778bf1e3',
    messagingSenderId: '915695183066',
    projectId: 'campusflow-11146',
    authDomain: 'campusflow-11146.firebaseapp.com',
    storageBucket: 'campusflow-11146.firebasestorage.app',
    measurementId: 'G-E9K6DQ459K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYJYXnCizDjEOdSzxt5jBYf7FOh9vccpw',
    appId: '1:915695183066:android:325d3149e672616a8bf1e3',
    messagingSenderId: '915695183066',
    projectId: 'campusflow-11146',
    storageBucket: 'campusflow-11146.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO0Qui27tDOwASOzAHaMXNt21p5POaGeA',
    appId: '1:915695183066:ios:4f2ce36ec91cba088bf1e3',
    messagingSenderId: '915695183066',
    projectId: 'campusflow-11146',
    storageBucket: 'campusflow-11146.firebasestorage.app',
    iosBundleId: 'com.example.campusFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO0Qui27tDOwASOzAHaMXNt21p5POaGeA',
    appId: '1:915695183066:ios:4f2ce36ec91cba088bf1e3',
    messagingSenderId: '915695183066',
    projectId: 'campusflow-11146',
    storageBucket: 'campusflow-11146.firebasestorage.app',
    iosBundleId: 'com.example.campusFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDaaP2LkXC5EKv7bXmElsYTjf7FPrGTzM',
    appId: '1:915695183066:web:c92bbfa4facf2ae18bf1e3',
    messagingSenderId: '915695183066',
    projectId: 'campusflow-11146',
    authDomain: 'campusflow-11146.firebaseapp.com',
    storageBucket: 'campusflow-11146.firebasestorage.app',
    measurementId: 'G-D4MT7SNC3E',
  );
}
